### ISSUE TITLE
貌似时区报错

### ISSUE THREAD

**Issue by LevineWoo** [sagan/ptool#1]
版本：0.1.0
平台：windows 11
网络：广东电信/机场线路（proxy)均测试过
报错内容：time="2023-05-12T10:32:59+08:00" level=error msg="Error: failed to create site audiences: invalid site timezone: Asia/Shanghai\n"
测试站点：观众
测试方式：ptool status audiences -t
配置中我尝试默认注释和开启时区的参数，报错内容一致。

**Comment by sagan** [comment]
这个之前已经修过了，release 里没更新。我放一个最新编译的版本上来吧。
