### ISSUE TITLE
感谢和反馈

### ISSUE THREAD

**Issue by wen-long** [sagan/ptool#12]
### 感谢
我是想辅种.IYUUPlus 没跑成功,觉得太重了就放弃了
用 ptool 遇到点问题自己仓促的解决了下,最终跑成功了, 感谢提供了 IYUUPlus 之外的另一种选择

----------- 

### 反馈

iyuu 接口调用方面:
调用 App.Api.Hash 失败, http 报错  `非法请求：辅种间隔过于频繁`
试了下应该是因为条目数太多了, 我在 api.go 这块改成分批调用就不报错了, 这块建议改一下

配置文件方面: 
程序最好输出生效的配置文件路径

站点支持方面:
希望能支持猫站, 我在 tpl.go 加了就可以辅种, 不清楚其他功能有没有问题

种子下载方面:
我在猫站遇到了  `Oops! Forbidden: Too many request! Your download permission is frozen for about 4 hours.` 错误, 下载连续多次报错最好主动停止

**Comment by sagan** [comment]
感谢反馈。

iyuu  的 App.Api.Hash接口应该是限制一段时间(几个小时?)内只能调用1次。但单次访问最多能提交多少个infohash 未知（目前程序限制 2000个）。

最新开发版本 `ptool version` 会输出 ptool.toml 配置文件路径。

猫站我没有。在配置文件里直接加站点 ( type 设为 "nexusphp" ) 和在 tpl.go 里加效果是等价的。tpl 只是提供快捷配置方式，tpl 里站点的任何配置项也可以在配置文件里直接覆盖掉。

**Comment by wen-long** [comment]
更新一下新情况:

```
ERRO[0001] http response body                            body="{\"code\":400,\"data\":[],\"msg\":\"单次提交种子info_hash最多500个\"}" contentType=application/json
```
iyuu 似乎限制了单次请求的种子数量最多为 500
