### ISSUE TITLE
[Feature Request]关键词过滤

### ISSUE THREAD

**Issue by Left024** [sagan/ptool#13]
我是使用 ptool 把我几个空闲的 vps 用来刷流的
本地的 NAS 用来订阅剧集更新的时候自动下载

如此就导致了一个问题：当一个剧集更新的时候，有可能 ptool 抢先将它添加到了 vps 的客户端上

然后本地 Nas 再添加时因为 PT 站只允许一个地方下载所以就没有开始下载

能否添加一个关键词过滤功能？当种子标题包含配置文件中设置的关键词时不添加刷流任务

**Comment by sagan** [comment]
这个功能已经有了，只是文档里没写。。站点配置里加上：

```
# 刷流排除种子关键字列表。标题或副标题包含列表中任意项的种子不会被刷流任务选择
brushExcludes = ["keyword1", "keyword2"]
```

**Comment by Left024** [comment]
感谢感谢
