### ISSUE TITLE
hhanclub信息爬取错误

### ISSUE THREAD

**Issue by Havoc-whr** [sagan/ptool#15]
![imags_20240114_091231](https://github.com/sagan/ptool/assets/78606709/18ec8ecd-01b3-4f46-a5db-ca47930b7388)
发现了新大陆，工具简单直接。但hhanclub种子大小和上传、下载完成人数都没有识别，多次尝试都是如此，希望开发大佬能单独适配下该站点，如果是本人操作不当导致，还望多包涵😊😊😊。

**Comment by sagan** [comment]
开发版已经修过这个问题了。

可点击首页顶部 ✓ 号 - Details，从 AppVeyor 下载最新代码的自动构建结果。

**Comment by Havoc-whr** [comment]
> 开发版已经修过这个问题了。
> 
> 可点击首页顶部 ✓ 号 - Details，从 AppVeyor 下载最新代码的自动构建结果。

试过啦，完美解决，这个效率真的太强了！

**Comment by Havoc-whr** [comment]
hhanclub可以搜到资源，但从站免开始就一直没有添加过刷流。

**Comment by sagan** [comment]
这个站点全局站免时种子列表里不显示free标识，所以没有识别。之前改了一下应该可以了。
