### ISSUE TITLE
在chd下载到了hr种子并且删除了部分开始计hr的种子

### ISSUE THREAD

**Issue by az7139** [sagan/ptool#16]
![hr](https://github.com/sagan/ptool/assets/33395197/5a4a030d-d29f-4351-99b1-73ae3ed03ea1)
右下角蓝色小圆标的是hr标志,超过50%开始计hr
刷流3天后发现下载了11个hr种子,并且其中两个是下载超过50%后删除

**Comment by sagan** [comment]
可在配置文件站点区块用 `selectorTorrentHnR = ".hr"`  设置 HR 标记的 css 选择器（相对于种子的 `<tr>` 元素）。

运行 `ptool status <sitename> -t` 命令测试。HR 种子的 Free 栏应该有 ! 标记。
