### ISSUE TITLE
设置iyuuDomain无效

### ISSUE THREAD

**Issue by BlackPeton** [sagan/ptool#17]
iyuu无法连接，原因是原api.iyuu.cn域名备案问题，iyuu作者临时采用香港服务器。但是在ptool.yaml配置文件中设置iyuuDomain无效，运行iyuu相关命令还是访问默认域名。

配置文件已设置domain：
<img width="386" alt="截屏2024-02-02 09 04 11" src="https://github.com/sagan/ptool/assets/53968485/30983611-3888-4a32-b858-420a64221a1e">

运行iyuu命令，domain设置无效：
<img width="967" alt="截屏2024-02-02 09 03 41" src="https://github.com/sagan/ptool/assets/53968485/c0d5b6fe-00c0-43ab-8e77-fc3eb6ec3346">

**Comment by sagan** [comment]
用最新开发版本。点击首页顶部 ✓ 号 - Details，从 AppVeyor 下载最新代码的自动构建结果。

另外 iyuuDomain 需要设为 'http://hk.iyuu.cn/'。如果只写域名，默认使用 https。
