### ISSUE TITLE
朱雀无法获取种子列表

### ISSUE THREAD

**Issue by dmc420** [sagan/ptool#2]
ptool status zhuque -t -vvv
time="2023-07-01T10:09:31+08:00" level=debug msg="ptool start: [ptool status zhuque -t -vvv]"
time="2023-07-01T10:09:31+08:00" level=info msg="config file: C:\\Users\\xxx/.config/ptool/ptool.toml"
time="2023-07-01T10:09:31+08:00" level=debug msg="Read config file C:\\Users\\xxx/.config/ptool/ptool.toml"
time="2023-07-01T10:09:31+08:00" level=trace msg="FetchUrl url=https://zhuque.in/ hasCookie=true"
time="2023-07-01T10:09:32+08:00" level=trace msg="FetchUrl response status=200"
time="2023-07-01T10:09:32+08:00" level=trace msg="FetchUrl url=https://zhuque.in/api/user/getMainInfo hasCookie=true"
time="2023-07-01T10:09:33+08:00" level=trace msg="FetchUrl response status=200"
time="2023-07-01T10:09:33+08:00" level=trace msg="FetchJson response: len=-1"
Site    zhuque         ↑: 34.95GiB                ↓: 60MiB                   UserName: xxx

Errors:
Error get site zhuque status: error=cann't get site zhuque torrents: not implemented yet

根据log访问https://zhuque.in/api/user/getMainInfo
网页显示
`Missing CSRF.`

**Comment by sagan** [comment]
非 NexusPHP 的站点还没有做“获取站点种子”的功能 (not implemented yet)。这些站点本程序目前只支持辅种，不支持刷流。
