### ISSUE TITLE
馒头的cookie复制过来并没有用

### ISSUE THREAD

**Issue by a350844866** [sagan/ptool#23]
![image](https://github.com/sagan/ptool/assets/29751183/e37bfa14-d4f4-4e4c-8542-1c6073c7f699)
是否是馒头站的问题还是这个工具的问题呢。新手，第一次用

这是我的配置文件 
![image](https://github.com/sagan/ptool/assets/29751183/e66d915c-a55d-4e45-9cf5-29177466464f)

执行了一下站点状态的查询
![image](https://github.com/sagan/ptool/assets/29751183/3ab4e043-d1fe-456f-87f9-87398d179de3)

**Comment by sagan** [comment]
请使用最新开发版程序。

**Comment by a350844866** [comment]
大佬，目前使用您的开发版本似乎还有一点小问题，我用了两台vps进行刷流，每台都有一个qb和ptool，是刷同一个mteam账号，cookie也是两个，现在有一台vps显示登录过期。
![image](https://github.com/sagan/ptool/assets/29751183/92b517cd-014b-459b-8e89-6845d1f14216)


所以我刚刚又换了一个cookie给它，但是还是显示过期，请问是咋回事

**Comment by a350844866** [comment]
> 大佬，目前使用您的开发版本似乎还有一点小问题，我用了两台vps进行刷流，每台都有一个qb和ptool，是刷同一个mteam账号，cookie也是两个，现在有一台vps显示登录过期。 ![image](https://private-user-images.githubusercontent.com/29751183/318322304-92b517cd-014b-459b-8e89-6845d1f14216.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5MzkwMjIsIm5iZiI6MTcxMTkzODcyMiwicGF0aCI6Ii8yOTc1MTE4My8zMTgzMjIzMDQtOTJiNTE3Y2QtMDE0Yi00NTliLThlODktNjg0NWQxZjE0MjE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAxVDAyMzIwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUzNzdiY2I0NmUxNzE2ZDE0Y2NmNGVlYTgxZmQ1M2M0NDU1ZGFmZWZlN2IxM2Q1YTcwZjYwYjRhNDgxNTIzNjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UEC-a-vaex2ghhCW5qtH_POJFhfEEkCjeRDc6_3zMwQ)
> 
> 所以我刚刚又换了一个cookie给它，但是还是显示过期，请问是咋回事

忘记说了，另外一台VPS一直可以。不知道是为啥，好像不太像是超时的问题，因为另外一台时间应该更久。。

VPS（可用的一台）是位于内地腾讯云的 

VPS（目前显示登录过期的）是位于美国加州的

**Comment by sagan** [comment]
有开启二级验证吗（設置 - 安全設定 - 啟用密碼+動態驗證碼二級驗證）。这种情况下 cookie 可能绑定 IP。

可尝试使用 token 鉴权方式，在配置文件里去掉 cookie 这行，加上下面这行：

```
httpHeaders = [["x-api-key", "xxx-xxx-xxx"]]
```

xxx-xxx-xxx 是 mteam 的个人 token。在  "設置 - 實驗室 - 存取令牌" 页面创建。

**Comment by a350844866** [comment]
感谢大佬，已解决
