### ISSUE TITLE
hdhome站点cookie无效

### ISSUE THREAD

**Issue by Havoc-whr** [sagan/ptool#25]
无论怎么更新或是手动替换hdhome站点cookie始终显示无效，cookie在其他工具中测试是有效的，不知道是不是工具的问题

**Comment by sagan** [comment]
该站点 cookie 严格绑定 ua。目前程序默认使用 chrome122。

可在配置文件里站点配置区块手动指定 ua :

```
userAgent = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36'
```

**Comment by Havoc-whr** [comment]
> 该站点 cookie 严格绑定 ua。目前程序默认使用 chrome122。
> 
> 可在配置文件里站点配置区块手动指定 ua :
> 
> ```
> userAgent = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36'
> ```

![Clip_2024-04-03_11-15-04](https://github.com/sagan/ptool/assets/78606709/bcea466a-f9c9-42e9-a85e-f5fca1a28d64)
不知道是否理解有误，按图中所示设置userAgent仍不可用

**Comment by sagan** [comment]
使用 curl 测试：

```
curl -I https://hdhome.org/ -H "Cookie: cookie_here" -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36"
```

如果 cookie 和 ua 匹配，那么应该返回 200。否则用对应的浏览器重新获取 cookie。另外当前使用的 IP 地址也可能有影响。

**Comment by Havoc-whr** [comment]
> 使用 curl 测试：
> 
> ```
> curl -I https://hdhome.org/ -H "Cookie: cookie_here" -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36"
> ```
> 
> 如果 cookie 和 ua 匹配，那么应该返回 200。否则用对应的浏览器重新获取 cookie。另外当前使用的 IP 地址也可能有影响。

![Clip_2024-04-03_16-39-59](https://github.com/sagan/ptool/assets/78606709/110f64b3-e2b3-4380-af46-3fa0097fc250)
应该是匹配的，没错

**Comment by Havoc-whr** [comment]
![Clip_2024-04-03_16-54-16](https://github.com/sagan/ptool/assets/78606709/75f98c7c-6d48-46fc-9341-d0aefcaeff9f)
搜索功能是NoResult，cookie更新的cookie也显示不可用

**Comment by Havoc-whr** [comment]
![Clip_2024-04-03_16-56-14](https://github.com/sagan/ptool/assets/78606709/e04817b5-3676-45a1-b122-ab7869e11bcd)
搜索显示NoResult

**Comment by sagan** [comment]
运行命令时加上 -vvv 调试参数： `ptool status hdhome -t -vvv` 。最常见的是 status=403 错误。但是你 curl 能成功但是 ptool 失败我也没遇到这种情况。

**Comment by Havoc-whr** [comment]
> 运行命令时加上 -vvv 调试参数： `ptool status hdhome -t -vvv` 。最常见的是 status=403 错误。但是你 curl 能成功但是 ptool 失败我也没遇到过这种情况。

![Clip_2024-04-07_11-37-46](https://github.com/sagan/ptool/assets/78606709/8f5531ec-b36e-4234-bf70-fa1ec0027001)
有些奇怪了😂

**Comment by zzzsgdhr** [comment]
我也遇到了同样的问题 请问该怎么解决？目前配置了八个站点 只有mteam可以正常运行
<img width="862" alt="屏幕截图 2024-04-26 142223" src="https://github.com/sagan/ptool/assets/42145971/e0c9ee14-3a67-45f0-b7f2-9a1f37b0e32c">

**Comment by Havoc-whr** [comment]
> 我也遇到了同样的问题 请问该怎么解决？目前配置了八个站点 只有mteam可以正常运行 <img alt="屏幕截图 2024-04-26 142223" width="862" src="https://private-user-images.githubusercontent.com/42145971/325869129-e0c9ee14-3a67-45f0-b7f2-9a1f37b0e32c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxMjQ3NzEsIm5iZiI6MTcxNDEyNDQ3MSwicGF0aCI6Ii80MjE0NTk3MS8zMjU4NjkxMjktZTBjOWVlMTQtM2E2Ny00NWYwLWI3ZjItOWExZjM3YjBlMzJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI2VDA5NDExMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY4NmU0Yjc1MjAxODIwZWEzNTI1YjBjYjFiMDk5NWYzMzFmOTI2ZmRmMWJkNGNkZGVjMmNjNzZiOTc5M2M5ZTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NE8Guh4XQ5enbGwy_gG0IqAp46ZJa8RvNJn2ZWMl6n4">

配置对了嘛，我是搜不出东西，不是站点错误

**Comment by merlin0531** [comment]
time="2024-04-30T21:32:38+08:00" level=trace msg="Site GetStatus got no data, possible a parser error"
time="2024-04-30T21:32:38+08:00" level=trace msg="Cann't find torrents list container element."
这个问题应该怎么解决？
