### ISSUE TITLE
启动pttime刷流指令报错

### ISSUE THREAD

**Issue by surjur** [sagan/ptool#27]
./ptool status pttime -t 测试没有问题
![image](https://github.com/sagan/ptool/assets/7477889/7d17e578-b8fa-47f5-9ec4-5396d60f2e7a)

./ptool brush local pttime 报错 Error: no sites successed.
![image](https://github.com/sagan/ptool/assets/7477889/d263465f-c2d5-4392-b132-fd99564b687f)

**Comment by sagan** [comment]
因为没有找到任何适合刷流的种子。

使用 `ptool status pttime -t --score` 测试，会显示种子的刷流评分(score)，> 0 才会被添加。
