### ISSUE TITLE
删除刷流任务

### ISSUE THREAD

**Issue by heliveth** [sagan/ptool#28]
首先感谢作者，非常好用的工具。
我想问删除刷流任务的条件可否更多样化，比如自动移除添加超过 x 周且无上传流量的（或者上传小于 y 的）刷流任务。

还有关于辅种任务，如果是iyuu或者reseed不支持的站点可以辅种吗？有没有可能用prowlarr或者jackett来进行辅种。另外是否有可能作为外部程序被qb调用？假设下载完成就自动调用ptool搜索有没有可辅种的站点？

非常感谢

**Comment by sagan** [comment]
刷流功能一直有计划重写（提高刷流效率、更多可选项）。但我自己现在不怎么刷流了，所以没太大动力改这块。再等等吧。

辅种有考虑增加使用 NP 的 pieces-hash 接口辅种功能(类似 [Reseed-Puppy](https://github.com/Reseed-Puppy/Reseed-Puppy))。iyuu 辅种方式不能下载完成立即查询，因为 iyuu 的 API 接口有访问频率限制，每几小时只能查询1次 info hash。

**Comment by JackyWay** [comment]
@sagan 我觉得这个刷流工具挺棒的，目前刷红叶效果还不错，之前其他工具未能很好的判断，导致刷流过程下载也增加了，希望作者有空继续优先，感谢。

**Comment by heliveth** [comment]
今天遇到一个情况，ptool自动删除了一些无用的刷流任务包括原始文件。结果导致被辅种到其他站点的任务开始自动重新下载，估计是因为源文件被删除。有没有可能在删除任务的时候，同时删除同hash的所有任务（会在不同的分类里面）？感谢。

**Comment by sagan** [comment]
改了下。现在刷流删种时，如果对应文件存在其它种子，不删除硬盘里文件。

**Comment by sagan** [comment]
刷流只会删除 `_brush` 分类里的种子。你可以将添加的辅种种子也设为该分类即可。

**Comment by heliveth** [comment]
理论上可以，但是如果辅种有几百个，不大可能一个个去追踪有没有相同种子的辅种任务。作为刷流用途，如果一个种子没有刷流的效果了，自然是删除（包括源文件）比较合理，还可以回收占用的硬盘空间。从刷流的逻辑来看，目前刷流任务只会删除_brush分类里的种子（包括源文件），这很好，但是如果能同时删除相同源文件的其他辅种任务就更人性化了。感谢

**Comment by sagan** [comment]
在自动化辅种工具里，将添加的辅种种子的分类设为”与源种子分类相同“即可。ptool 自带的 iyuu 命令默认已经这样做。

如果你的辅种工具无法设置辅种种子的分类，你可以：

1. 在 qb 里给 `_brush` 分类设置单独的 save path。
2. 定时运行 ptool，将该 save path 里所有种子分类设为 `_brush`: 
 
```
ptool show local --save-path "E:\Downloads\_brush" --show-info-hash-only _done | ptool setcategory local _brush -
```

**Comment by heliveth** [comment]
感谢回复。。 _brush分类一直有设置单独path。
亦或者，有办法让 ptool 操作多个分类吗？比如 _brush; _brush.cross-seed; iyuu 这样？但是我的理解，这样好像也无法解决删除刷流任务的同时删除同种的所有辅种任务

**Comment by heliveth** [comment]
已经发展到qb里面只有45个刷流任务，但是_brush文件夹里面却有281个项目了。应该是3个礼拜前的那个更新“
### 改了下。现在刷流删种时，如果对应文件存在其它种子，不删除硬盘里文件。” 
我不知道这个更新是不是越改越糟。现在导致刷流任务删除了，但是因为同时有辅种任务所以种子文件没有删。
有点失控了，拜托可不可以删除刷流任务的同时，删除同hash的所有任务连同种子文件？感谢

> 理论上可以，但是如果辅种有几百个，不大可能一个个去追踪有没有相同种子的辅种任务。作为刷流用途，如果一个种子没有刷流的效果了，自然是删除（包括源文件）比较合理，还可以回收占用的硬盘空间。从刷流的逻辑来看，目前刷流任务只会删除_brush分类里的种子（包括源文件），这很好，但是如果能同时删除相同源文件的其他辅种任务就更人性化了。感谢

**Comment by heliveth** [comment]
已解决，根据大佬提供的归类命令行。谢谢
