### ISSUE TITLE
[Feature Request]自动签到

### ISSUE THREAD

**Issue by Left024** [sagan/ptool#3]
感谢开发如此好用的软件
希望可以添加一个自动签到的功能~

**Comment by sagan** [comment]
我想过签到，但是觉得不适合做，因为：

1. 这个程序设计是无状态的(stateless)，而签到需要跟踪状态(检测失败、延时多次重试)
2. 很多站点签到需要过CF盾、验证码、答题等人机识别，这些都不太好弄。

**Comment by Left024** [comment]
理解了，谢谢回复
