### ISSUE TITLE
m-team刷流失败

### ISSUE THREAD

**Issue by zzzsgdhr** [sagan/ptool#32]
<img width="778" alt="屏幕截图 2024-04-30 123731" src="https://github.com/sagan/ptool/assets/42145971/12407722-e66b-4ea7-975d-5dd98b5abac3">
<img width="859" alt="屏幕截图 2024-04-30 123819" src="https://github.com/sagan/ptool/assets/42145971/854c2016-e431-4641-960b-a340758af8c5">
如图 cookie确认没有错误 但是会报错401

**Comment by JarmoHu** [comment]
同问题

**Comment by sagan** [comment]
M-Team 现在不支持 Cookie，必须使用 token 方式鉴权。

参考 [ptool.example.toml](https://github.com/sagan/ptool/blob/master/config/ptool.example.toml) 文件里的 mteam 示例配置。

**Comment by zzzsgdhr** [comment]
> M-Team 现在不支持 Cookie，必须使用 token 方式鉴权。
> 
> 参考 [ptool.example.toml](https://github.com/sagan/ptool/blob/master/config/ptool.example.toml) 文件里的 mteam 示例配置。

谢谢 昨天没看到配置实例已经改变了 现在根据示例 已经配置成功了
