### ISSUE TITLE
hdsky

### ISSUE THREAD

**Issue by Havoc-whr** [sagan/ptool#35]
作者是否可以增加对hdsky站点的支持？

**Comment by sagan** [comment]
我没有这个站。

nexusphp 的任意站点可以参考 README 自行在配置文件里添加，即使没有内置支持。

**Comment by Havoc-whr** [comment]
> 我没有这个站。
> 
> nexusphp 的任意站点可以参考 README 自行在配置文件里添加，即使没有内置支持。

好吧，在开issue之前尝试过，搜不出种子，连接是正常的，可能是站点有改动吧
