### ISSUE TITLE
配置项torrentsUrl

### ISSUE THREAD

**Issue by Jikexiaobai** [sagan/ptool#4]
我目前刷馒头站点 设置了3个sites 来请求torrents.php和adult.php还有music.php三个列表 但这种方法有些臃肿 建议torrentsUrl配置项可以设置为多参数 避免过多的sites
知道作者该程序是自用，但希望可以采纳

**Comment by sagan** [comment]
已经有这个功能了，只是文档里没写。。配置项 torrentsExtraUrls 可以配置站点额外的种子页面url，刷流时也会抓这些页面里的种子。并且[默认站点配置](https://github.com/sagan/ptool/blob/master/site/tpl/tpl.go)的馒头(type = "mteam”)的 torrentsExtraUrls 里已经包含了 adult.php。

如果要加入 music.php，目前可以这样写

```
[[site]]
type = "mteam"
torrentsExtraUrls  = ["adult.php", "music.php"]
```
