### ISSUE TITLE
[bugfix]刷流时候保留空间和删种不起作用

### ISSUE THREAD

**Issue by JackyWay** [sagan/ptool#40]
感谢作者开发该软件。
在刷流期间，不停的添加任务，没有按照保留5G空间的设计原则，导致硬盘空间爆了，而且也不会自动删除，请问能否修复？谢谢

==========
删种（删除 BT 客户端里旧的刷流种子）规则：

未下载完成的种子免费时间临近截止时，删除种子或停止下载（只上传模式）。
硬盘剩余可用空间不足（默认保留 5GiB）时，开始删除没有上传速度的种子。
未下载完成的种子，如果长时间没有上传速度或上传/下载速度比例过低，也可能被删除。

![brush](https://github.com/sagan/ptool/assets/53031570/05ae4414-f7e6-4427-a5fc-9c5c4b8b017f)

**Comment by sagan** [comment]
请确认下 _brush 分类的下载目录里面是否存在已经在 qBittorrent 里删除了的种子的文件。

现在刷流删种时，如果种子硬盘上的文件对应还存在非_brush 分类里的其它种子（通常是第三方辅种工具自动添加的），则只删除 qb 里种子，不删除硬盘里文件。这个功能没有充分测试过（我自己现在不怎么刷流了），不能保证没有问题。

**Comment by JackyWay** [comment]
> 请确认下 _brush 分类的下载目录里面是否存在已经在 qBittorrent 里删除了的种子的文件。
> 
> 现在刷流删种时，如果种子硬盘上的文件对应还存在非_brush 分类里的其它种子（通常是第三方辅种工具自动添加的），则只删除 qb 里种子，不删除硬盘里文件。这个功能没有充分测试过（我自己现在不怎么刷流了），不能保证没有问题。

有其他工具vertex在一起刷流和删种，有哪个参数可以限制磁盘空间低于多少G的时候，就不再添加种子？

**Comment by heliveth** [comment]
很有可能是你的 _brush 分类的种子已经删空了，但是因为有第三方辅种工具自动添加的其他种子，导致硬盘里面的文件没有被删除，所以就没有空间了。目前的ptool已经无种可删，也就腾不出空间了。
其实我还是建议ptool能不能删种_brush的同时删除其他分类的相同种子并移除硬盘文件回收硬盘空间，或者至少给一个设置项。因为毕竟是刷流，辅种可以刷多个站点，这个很好，但是硬盘空间不可控也是一个很大的问题。

**Comment by sagan** [comment]
如果因为 ptool 添加的刷流种子被第三方工具自动辅种，导致刷流删种时没有删除文件，那么只需要将那些第三方工具添加的辅种种子的分类也设为 `_brush`  以允许 ptool 管理其即可。即定期运行：

```
ptool show local --save-path "E:\Downloads\_brush" --show-info-hash-only _done | ptool setcategory local _brush -
```

其中 "E:\Downloads\_brush" 是 qb 里 `_brush` 分类种子的保存路径。

**Comment by heliveth** [comment]
这个是个好办法，可是怎么解决删除硬盘文件的问题？可以 _brush 分类里面删除同hash种子的同时删除硬盘文件吗？

**Comment by sagan** [comment]
目前设计是，删除 _brush 分类种子时，如果对应硬盘路径没有其他种子（或者其他种子也在本次删除列表里）,自动删除硬盘文件。

**Comment by heliveth** [comment]
所里理论上就算硬盘路径里有对应的种子，迟早也是会被删掉的就对了。已经按上面的说明改好，我再观察几天回来汇报。谢谢大佬

**Comment by heliveth** [comment]
实测可用，大佬牛皮
