### ISSUE TITLE
没看出为什么都是 score=0

### ISSUE THREAD

**Issue by 11800111** [sagan/ptool#44]
麻烦帮忙看下，🙏

`DEBU[0000] ptool start: [./ptool brush local discfan -vvv]
DEBU[0000] tty=true, width=81, height=23
INFO[0000] config file: /root/.config/ptool/ptool.toml
DEBU[0000] Read config file /root/.config/ptool/ptool.toml
TRAC[0000] Create site nexusphp http client with specs 771,4865-4866-4867-49195-49199-49196-49200-52393-52392-49171-49172-156-157-47-53,23-13-27-16-51-65281-45-5-17513-0-35-43-65037-11-18-10,29-23-24,0
1:65536,2:0,4:6291456,6:262144|15663105|0|m,a,s,p

false
5
INFO[0000] Brush client local site discfan
TRAC[0000] FetchUrlWithAzuretls url=https://discfan.net/torrents.php hasCookie=true
TRAC[0001] FetchUrlWithAzuretls response status=200
TRAC[0001] nptr: map elsLen=50, len=1
TRAC[0001] nptr: container node=&{0xc0001d01c0 0xc0001d0380 0xc00038fa40 0xc0001d0230 <nil> 3 tbody tbody  []}, id=, class=
TRAC[0001] nptr: header node=&{0xc0001d02a0 0xc0001d03f0 0xc0001d1810 <nil> 0xc0001d1880 3 tr tr  []}, id=, class=
TRAC[0001] np parse fieldColumIndex: map[leechers:6 name:1 process:-1 seeders:5 size:4 snatched:7 time:3]
INFO[0001] Brush Options: minDiskSpace=1GiB, slowUploadSpeedTier=100KiB, torrentUploadSpeedLimit=10MiB/s, maxDownloadingTorrents=6, maxTorrents=9999, minRatio=0.200000
TRAC[0001] rateSiteTorrent score=0 name=The Bodyguard from Beijing AKA Zhong Nan Hai bao biao 1994 2160p GBR UHD Blu-ray HEVC LPCM 2.0-InfectedMind, free=false, rtime=151200, seeders=23, leechers=1, note=
TRAC[0001] rateSiteTorrent score=0 name=The Bodyguard from Beijing AKA Zhong Nan Hai bao biao 1994 1080p GBR Blu-ray AVC LPCM 2 0-InfectedMind, free=true, rtime=183600, seeders=39, leechers=1, note=
TRAC[0001] rateSiteTorrent score=0 name=A Man Called Tiger 1973 1080p GBR Blu-ray AVC LPCM 2.0-ApheX, free=false, rtime=280800, seeders=24, leechers=2, note=
TRAC[0001] rateSiteTorrent score=0 name=Love on Delivery 1994 1080p USA Blu-ray AVC DTS-HD MA 2.0-MAXiMUMBiTRATE, free=false, rtime=417600, seeders=23, leechers=0, note=
TRAC[0001] rateSiteTorrent score=0 name=Love on Delivery 1994 BluRay 1080p AVC DTS-HD MA 2.0-N!ck, free=false, rtime=86400, seeders=49, leechers=5, note=
TRAC[0001] rateSiteTorrent score=0 name=Tiger Over Wall 1980 GER PAL DVD9-19TH, free=false, rtime=86400, seeders=25, leechers=0, note=
TRAC[0001] rateSiteTorrent score=0 name=Dynamo 1978 GER PAL DVD9 - Discfan, free=false, rtime=133200, seeders=15, leechers=0, note=
TRAC[0001] rateSiteTorrent score=0 name=Struggle Through Death 1979 GER PAL DVD9-19TH, free=false, rtime=187200, seeders=16, leechers=0, note=
TRAC[0001] rateSiteTorrent score=0 name=The Eye Trilogy 20th Anniversary Commemorative Box Set 2002-2005 1080p HKG Blu-ray AVC TrueHD 5.1-MTeam, free=false, rtime=205200, seeders=18, leechers=0, note=
TRAC[0001] rateSiteTorrent score=0 name=Samurai Banners 1967 GER PAL DVD9, free=false, rtime=237600, seeders=5, leechers=3, note=
TRAC[0001] rateSiteTorrent score=0 name=Once Upon a Time in China 5 1994 GER PAL DVD9, free=false, rtime=244800, seeders=13, leechers=0, note=
TRAC[0001] rateSiteTorrent score=0 name=The Eighteen Jade Arhats 1979 GER PAL DVD9-19TH, free=false, rtime=248400, seeders=20, leechers=0, note=
TRAC[0001] rateSiteTorrent score=0 name=The Flying Dagger 1969 USA Blu-ray 1080p AVC DTS-HD MA 2.0-DIY@Hero, free=false, rtime=34168436, seeders=1, leechers=2, note=
TRAC[0001] rateSiteTorrent score=0 name=The 25th Anniversary Sing For All The World PolyGram 1995 NTSC LD, free=true, rtime=17940, seeders=1, leechers=16, note=
TRAC[0001] rateSiteTorrent score=0 name=Super Dragon - The Bruce Lee Story 1974 NTSC DVD5, free=true, rtime=136800, seeders=13, leechers=0, note=
TRAC[0001] rateSiteTorrent score=0 name=The Bodyguard from Beijing 1994 BDRip 1080p x265 10bit AC3 2Audio-DGB, free=true, rtime=169200, seeders=11, leechers=0, note=
TRAC[0001] rateSiteTorrent score=0 name=Bo bui gai wak 2006 1080p Blu-ray AVC DTS-HD MA 5.1-NOGROUP, free=false, rtime=17940, seeders=1, leechers=11, note=
TRAC[0001] rateSiteTorrent score=0 name=Love on Delivery 1994 720p BluRay FLAC2.0 x264-PTer, free=false, rtime=38760, seeders=2, leechers=0, note=
TRAC[0001] rateSiteTorrent score=0 name=Bruce Lee: The Man, The Myth 1976 1080p WEB-DL DDP2.0 H.264-Secrecy, free=false, rtime=54780, seeders=4, leechers=0, note=
TRAC[0001] rateSiteTorrent score=0 name=Rurouni Kenshin 2012 BluRay 1080p x264 AC3-CMCT , free=false, rtime=73740, seeders=2, leechers=0, note=
TRAC[0001] rateSiteTorrent score=0 name=Hei Mian Ren 1980 NTSC DVD5, free=false, rtime=80160, seeders=4, leechers=0, note=
TRAC[0001] rateSiteTorrent score=0 name=The Shaolin Temple 1982 2160p UHD BluRay x265 10bit DV HDR DTS-HD MA 5.1 mUHD-FRDS, free=false, rtime=80340, seeders=13, leechers=0, note=
TRAC[0001] rateSiteTorrent score=0 name=The Bodyguard from Beijing 1994 GBR Blu-ray 1080p AVC LPCM.2.0 XQN@CMCT, free=false, rtime=81900, seeders=4, leechers=0, note=
TRAC[0001] rateSiteTorrent score=0 name=You Are My Sunshine 2005 BluRay 1080p x264 DTS-CMCT, free=false, rtime=85740, seeders=7, leechers=0, note=
TRAC[0001] rateSiteTorrent score=0 name=The Con Artists 2014 HKG BluRay 1080p x264 DTS 2Audios-CMCT, free=false, rtime=86400, seeders=11, leechers=0, note=
TRAC[0001] rateSiteTorrent score=0 name=Anti-Terrorism Investigators S01 1080p AMZN WEB-DL DDP2.0 H.264-JPTVclub, free=false, rtime=90000, seeders=2, leechers=0, note=
TRAC[0001] rateSiteTorrent score=0 name=Oldboy AKA Oldeuboi 2003 1080p GBR Blu-ray AVC DTS-HD MA 7.1, free=false, rtime=97200, seeders=10, leechers=0, note=
TRAC[0001] rateSiteTorrent score=0 name=Hero 2002 1080p Blu-ray Remux AVC DTS-HD MA2.0-HDS, free=false, rtime=111600, seeders=2, leechers=0, note=
TRAC[0001] rateSiteTorrent score=0 name=Mirai no Mirai 2018 1080p BluRay Remux AVC FLAC 5.1 4Audio-ADE, free=false, rtime=133200, seeders=1, leechers=3, note=
TRAC[0001] rateSiteTorrent score=0 name=Umimachi Diary 2015 1080p KOR Blu-ray AVC DTS-HD MA 5.1-ANKO, free=false, rtime=169200, seeders=4, leechers=0, note=
TRAC[0001] rateSiteTorrent score=0 name=Father 2016 1080p WEB-DL H.265 AAC-ADWeb, free=false, rtime=169200, seeders=2, leechers=0, note=
TRAC[0001] rateSiteTorrent score=0 name=Fearless 2006 2160p WEB-DL AVC AAC-QHstudIo, free=false, rtime=173636, seeders=3, leechers=0, note=
TRAC[0001] rateSiteTorrent score=0 name=Tokyo Grand Guignol 2015 1080p Blu-ray AVC DTS-HD MA 5.1-BluRHD, free=false, rtime=183600, seeders=2, leechers=0, note=
TRAC[0001] rateSiteTorrent score=0 name=Memories of Peking S01 2019 1080p Hami WEB-DL H.264 AAC-HHWEB, free=false, rtime=190800, seeders=5, leechers=1, note=
TRAC[0001] rateSiteTorrent score=0 name=Our Little Sister AKA Umimachi Diary 2015 2160p KOR UHD Blu-ray DV HDR10+ HEVC DTS-HD MA 5.1-ANKO, free=false, rtime=194400, seeders=6, leechers=0, note=
TRAC[0001] rateSiteTorrent score=0 name=CCTV6 Long xu gou 1952 HDTV 1080i H264 AAC, free=false, rtime=205200, seeders=6, leechers=0, note=
TRAC[0001] rateSiteTorrent score=0 name=BTV Nan Ren Bang Complete 720p HDTV x264-HDCTV, free=false, rtime=212400, seeders=1, leechers=0, note=
TRAC[0001] rateSiteTorrent score=0 name=Fist of Fury 2 aka Chinese Connection 2 1977 GER PAL DVD9, free=false, rtime=248400, seeders=15, leechers=0, note=
TRAC[0001] rateSiteTorrent score=0 name=Gaiji Keisatsu Black Dawn 2012 1080p friDay WEB-DL H.264 AAC-PTerWEB, free=false, rtime=255600, seeders=1, leechers=0, note=
TRAC[0001] rateSiteTorrent score=0 name=The Master 1992 BluRay 1080p AVC TrueHD 7 1-CHDBits, free=false, rtime=273600, seeders=2, leechers=0, note=
TRAC[0001] rateSiteTorrent score=0 name=Concatenate Traps 2012 S01 Complete 2160p 60fps WEB-DL H.265 10bit AAC 2.0-QHstudIo, free=false, rtime=291600, seeders=3, leechers=0, note=
TRAC[0001] rateSiteTorrent score=0 name=The Shaolin Temple 1982 1080p UHD BluRay FLAC1.0 DoVi HDR10 x265-PTer, free=false, rtime=295200, seeders=4, leechers=0, note=
TRAC[0001] rateSiteTorrent score=0 name=God of War Zhao Yun 2016 S01 Complete 2160p 60fps WEB-DL HEVC 10bit AAC-QHstudIo, free=false, rtime=309600, seeders=9, leechers=0, note=
TRAC[0001] rateSiteTorrent score=0 name=Angel Terminators 1992 GER 2in1 BluRay 1080p AVC DD 2.0-FFansDIY@至尊宝, free=false, rtime=320400, seeders=23, leechers=1, note=
TRAC[0001] rateSiteTorrent score=0 name=Nana Mizuki Live Grace OpusII & Union 2012-2013 Blu-Ray 1080p AVC DTS-HD MA 5.1 @U2, free=false, rtime=338400, seeders=5, leechers=0, note=
TRAC[0001] rateSiteTorrent score=0 name=Snake in the Monkey's Shadow 1979 GER PAL DVD9, free=false, rtime=352800, seeders=14, leechers=0, note=
TRAC[0001] rateSiteTorrent score=0 name=Ninja the Protector 1986 GER PAL DVD5, free=false, rtime=352800, seeders=13, leechers=1, note=
TRAC[0001] rateSiteTorrent score=0 name=Discover The Great Silk Road S03 2012 1080p Hami WEB-DL H.264 AAC-HHWEB, free=false, rtime=360000, seeders=5, leechers=0, note=
TRAC[0001] rateSiteTorrent score=0 name=In the Name of People 2017 S01 Complete 2160p 60fps WEB-DL HEVC 10bit AAC-QHstudIo, free=false, rtime=363600, seeders=3, leechers=0, note=
TRAC[0001] rateSiteTorrent score=0 name=The New Legend of ShaoLin 1994 JPN Blu-ray 1080p AVC DTS-HD MA 5.1-DIY@Hero, free=false, rtime=367200, seeders=19, leechers=0, note=
INFO[0001] Current client local torrents: 0; Download speed / limit: 0B/s / 0B/s; Upload speed / limit: 0B/s / 0B/s;Free disk space: -1B;
INFO[0001] Fetched site discfan torrents: 50; Client add / modify / stall / delete torrents: 0 / 0 / 0 / 0. Msg:
Finish brushing 1 sites: successSites=0, skipSites=1; Added / Deleted torrents: 0 / 0 to client local
Error: no sites successed.
TRAC[0001] Exit. Closing resources
TRAC[0001] Close client local instance`

**Comment by 11800111** [comment]
现在有一些是非0的种子成功添加了，但是不太了解评分的机制

**Comment by sagan** [comment]
至少需要符合以下所有条件 score 才可能 > 0：
 
- 免费 free=tree
- 0 < 做种人数 seeders < 下载人数 leechers
- 发布时间 rtime (当前时间与种子发布时间差值秒数) < 一定值

评分机制是我当时拍脑袋写的，基本没改过。有很多优化余地。

**Comment by eqfae** [comment]
> 现在有一些是非0的种子成功添加了，但是不太了解评分的机制

你解决了吗 
Finish brushing 1 sites: successSites=0, skipSites=1; Added / Deleted torrents: 0 / 0 to client local
Error: no sites successed.
看到你的加-vvv参数 一眼全是 score=0
