### ISSUE TITLE
新版Qbittorrent 5.0默认会让文件移入回收站，而不是删除

### ISSUE THREAD

**Issue by fjh1997** [sagan/ptool#48]
详见：https://github.com/qbittorrent/qBittorrent/pull/20252

影响自动删除无用种子功能，可能需要调整api调用方式

**Comment by sagan** [comment]
看了下，这个程序不好处理。qb web api 没有提供“永久删除文件”参数。

不过下个版本 qb 应该会默认禁用回收站： https://github.com/qbittorrent/qBittorrent/pull/21528

**Comment by JarmoHu** [comment]
这个设置web端改不了，但可以通过修改qb配置文件改。新版好像默认禁用了
