### ISSUE TITLE
如何选择只刷电影分类的呢？

### ISSUE THREAD

**Issue by jeffreyouni** [sagan/ptool#49]
你好，请问如何选择只刷电影分类的呢？
brush local xxx 命令会刷符合的种子，包括电视剧等等，如何只刷电影分类的呢？因为下载的我也会看，但是我基本只看电影，不看电视剧。
谢谢。

**Comment by sagan** [comment]
最新版现在可以在站点配置里加入 `brushExcludeTags = ['电视剧']` 使刷流排除特定标签的种子。

种子的分类名也是标签，使用 `ptool . status -td u2 ` 查看：标题后面的 `// ["BDMV"]` 部分。

**Comment by jeffreyouni** [comment]
感谢回复，
请问对于这种所有种子的标签与标题里都没有“电视剧”，“标题”关键字的种子：
![image](https://github.com/user-attachments/assets/49a640c7-c71d-48b6-849d-1d3b68298510)
应该如何设置呢？只有 `类型: 电视剧`

这是我的配置：
![image](https://github.com/user-attachments/assets/c1d06b7e-10bd-4103-9e6b-5da26eefa998)

这是配置后的下载：
![image](https://github.com/user-attachments/assets/54426ba7-4e8a-45b2-bdad-a5cb96f46cd3)

![image](https://github.com/user-attachments/assets/4b5c0ccc-5c8c-4426-94ae-6988156617cb)

**Comment by sagan** [comment]
需要用昨天更新的最新版本。
