### ISSUE TITLE
【疑问】某些站点从未刷流过

### ISSUE THREAD

**Issue by Left024** [sagan/ptool#5]
用了大概半个月了，有些站点从来没有自动添加过种子，想知道是哪里的问题
btschool 和 haidan 从未自动添加过种子，其它站点到是根据定时任务一直在刷流
检查了下cookies正常，用命令搜索种子也能搜出来
想请教下是哪里的问题？

**Comment by sagan** [comment]
btschool 全站HR，刷流不会添加此类站点种子。

haidan 我看了下目前种子信息抓取有点小问题，没有获取到做种和下载人数。不满足选种条件也不会添加种子。

**Comment by Left024** [comment]
感谢回复~
或者可以根据这种情况针对性刷流？btschool 符合HR条件后再自动删除，虽然刷流效率低，但总比没有好
然后根据一定比率控制，比如我的命令是：
`ptool brush site1 site2 site3 sites4 btschool`
这五个站点中只有 btschool 是全站HR，比如说其他四个站点刷了十个种子，才安排 btschool 刷一个
不知我这个建议可不可行

**Comment by sagan** [comment]
很难检测种子是否已满足 HR 条件：

1. BT 客户端不知道种子的已做种时长。只能根据当前时间和种子完成时间推算。因为各种原因这个值和站点服务器端的统计可能有很大差异。
2. 抓取 myhr.php。这个靠谱些，但不同站点页面解析规则有差异，工作量很大。因为必须做到100%精确解析并且能够容忍站点UI变化。误删种分分钟封号。

有一种邪道是部分站点(比如btschool)只有下载完成才计算HR，所以可以下载进度到99%时直接删种。但是这种有点属于滥用规则了。

**Comment by sigfried8863** [comment]
> 理解了，感谢回复~

您好，能不能请教一下btschool的cookie应该如何获取，一直卡在这个环节。感谢~
