### ISSUE TITLE
PTool 从不同的2个站点同时下载同一个资源

### ISSUE THREAD

**Issue by jeffreyouni** [sagan/ptool#50]
你好，

PTool 从不同的2个站点同时下载同一个资源, 一个正在下载，一个正在校验。

![PixPin_2024-10-17_17-10-32](https://github.com/user-attachments/assets/528cbf2c-2d4f-4054-a04d-1950feee55cc)

Google了一下，都说要手动暂停一个，没法两个种子同个资源一起下载，因为下载的文件一直在变，校验不了，还会重复下载很多块。可以在一个下载完后再继续另一个以达成同时刷流的目的。

请问这样的情况会有问题吗，可以放任不管吗？如何避免呢？

谢谢。

**Comment by sagan** [comment]
改了下，现在刷流时会避免添加多个相同内容文件夹名称的种子。
