### ISSUE TITLE
磁盘空间获取错误，显示为 FreeSpace: -1B

### ISSUE THREAD

**Issue by yabbie** [sagan/ptool#6]
Win10环境下运行
ptool status local -t -vvv
time="2023-09-01T11:14:09+08:00" level=debug msg="ptool start: [ptool status local -t -vvv]"
time="2023-09-01T11:14:09+08:00" level=info msg="config file: ./ptool.toml"
time="2023-09-01T11:14:09+08:00" level=debug msg="Read config file ./ptool.toml"
Client  local          ↑Spd/Lmt: 0B / 50MiB/s     ↓Spd/Lmt: 0B / 20MiB/s     FreeSpace: -1B; Unfinished(All/DL): 0B/0B

Name                       InfoHash                                  Size      State  ↓S(/s)    ↑S(/s)    Seeds  Peers  Tracker
time="2023-09-01T11:14:09+08:00" level=trace msg="Exit. Closing resources"
time="2023-09-01T11:14:09+08:00" level=trace msg="Close client local instance"

-----------

ptool brush local _all
Finish brushing 3 sites: successSites=0, skipSites=3; Added / Deleted torrents: 0 / 0 to client local
Error: no sites successed

-----------
qb的web看是正常显示磁盘剩余空间的。
请问是什么原因呢？

**Comment by sagan** [comment]
qb 的 web ui api 有时返回磁盘剩余空间0，但实际硬盘空间充裕。原因还不明确。( 重现步骤：登录 web ui，打开 http://127.0.0.1:8080/api/v2/sync/maindata , 有时返回的 free_space_on_disk 为 0)

所以之前加了个处理尝试检测这种qb错误报告0剩余空间情形，然后将 FreeSpace 标记为 -1 (未知)。FreeSpace = -1 不会影响刷流任务添加种子。如果要查看刷流为什么不什么不加种子, 加上 -vvv 参数运行 ptool brush。
