### ISSUE TITLE
北邮人NexusPHP免费种好像识别有误

### ISSUE THREAD

**Issue by FovenX3** [sagan/ptool#7]
[TV][VCB-Studio][IDOLiSH7-偶像星愿-][IDOLiSH7][TV 01-17 Fin+SP][1080p][BDRip][MKV][2018.01][日漫]  (剩余时间：1天 21时)
爱娜娜 / i7 / アイドリッシュセブン | HEVC-10bit | 官方合集	
0	2023-10-18
19:13:30	49.32
GiB	1	49	0

time="2023-10-18T22:31:08+08:00" level=trace msg="rateSiteTorrent score=0 name=[TV][VCB-Studio][IDOLiSH7-偶像星愿-][IDOLiSH7][TV 01-17 Fin+SP][1080p][BDRip][MKV][2018.01][日漫], free=false, rtime=11858, seeders=1, leechers=50, note="

**Comment by FovenX3** [comment]
`<tr><td class="rowfollow nowrap" style="vertical-align: middle"><a href="upload.php?quote=338389" title="引用该种子发布"><div class="icons quote"></div></a></td><td class="rowfollow nowrap" style="padding: 0; vertical-align: middle"><div class="cat-icon-merge">
    <span class="cat-icon cat-404">
        <a href="torrents.php?cat=404" class="cat-link">动漫</a>
    </span>
    <span class="secocat-icon cat-404">
        <a href="torrents.php?cat=404&amp;secocat=19" class="secocat-link">动画</a>
    </span>
</div></td>
<td class="rowfollow"><table class="torrentname full transparentbg"><tbody><tr><td class="embedded" style="padding-right: 5px"><div class="icons sticky-buy inverse-y" title="竞价置顶至2023-10-20 19:15:57"></div></td><td class="embedded" style="width: 99%"><a target="_self" title="[TV][VCB-Studio][IDOLiSH7-偶像星愿-][IDOLiSH7][TV 01-17 Fin+SP][1080p][BDRip][MKV][2018.01][日漫]" href="details.php?id=338389&amp;hit=1"><span class="bold">[TV][VCB-Studio][IDOLiSH7-偶像星愿-][IDOLiSH7][TV 01-17 Fin+SP][1080p][BDRip][MKV][2018.01][日漫]</span></a>&nbsp;<img class="pro_free" src="/pic/trans.gif" title="不计下载量" alt=""> <span class="bold">(<span style="color: blue" title="">剩余时间：<span title="2023-10-20 19:15:57">1天 21时</span></span>)</span><br>爱娜娜 / i7 / アイドリッシュセブン | HEVC-10bit | 官方合集 </td><td class="embedded" style="text-align: right; "><a href="download.php?id=338389"><div class="icons download ml-4 mb-4" title="下载本种"></div></a><br><a id="bookmark0" href="javascript: bookmark(338389,0);"><div class="icons delbookmark ml-2" style="display: inline-block" title="收藏"></div></a></td>
</tr></tbody></table></td><td class="rowfollow"><span title="无新评论">0</span></td><td class="rowfollow nowrap">2023-10-18<br>19:13:30</td><td class="rowfollow">49.32<br>GiB</td><td class="rowfollow"><b><a href="details.php?id=338389&amp;hit=1&amp;dllist=1#seeders"><span style="color: #ff0000">1</span></a></b></td>
<td class="rowfollow"><b><a href="details.php?id=338389&amp;hit=1&amp;dllist=1#leechers">49</a></b></td>
<td class="rowfollow">0</td>
<td class="rowfollow"><span class="nowrap"><a class="Uploader_Name" href="/userdetails.php?id=366418"><span style="font-weight: bold">ruoqin</span></a></span><br><a href="badges.php?action=owners&amp;bid=2469" target="_target" title="μ’s徽章"><span class="boot-label-red" title="点击显示详情">μ’s</span></a></td></tr>`

**Comment by FovenX3** [comment]
```
<tr><td class="rowfollow nowrap" style="vertical-align: middle"><a href="upload.php?quote=338389" title="引用该种子发布"><div class="icons quote"></div></a></td><td class="rowfollow nowrap" style="padding: 0; vertical-align: middle"><div class="cat-icon-merge">
    <span class="cat-icon cat-404">
        <a href="torrents.php?cat=404" class="cat-link">动漫</a>
    </span>
    <span class="secocat-icon cat-404">
        <a href="torrents.php?cat=404&amp;secocat=19" class="secocat-link">动画</a>
    </span>
</div></td>
<td class="rowfollow"><table class="torrentname full transparentbg"><tbody><tr><td class="embedded" style="padding-right: 5px"><div class="icons sticky-buy inverse-y" title="竞价置顶至2023-10-20 19:15:57"></div></td><td class="embedded" style="width: 99%"><a target="_self" title="[TV][VCB-Studio][IDOLiSH7-偶像星愿-][IDOLiSH7][TV 01-17 Fin+SP][1080p][BDRip][MKV][2018.01][日漫]" href="details.php?id=338389&amp;hit=1"><span class="bold">[TV][VCB-Studio][IDOLiSH7-偶像星愿-][IDOLiSH7][TV 01-17 Fin+SP][1080p][BDRip][MKV][2018.01][日漫]</span></a>&nbsp;<img class="pro_free" src="/pic/trans.gif" title="不计下载量" alt=""> <span class="bold">(<span style="color: blue" title="">剩余时间：<span title="2023-10-20 19:15:57">1天 21时</span></span>)</span><br>爱娜娜 / i7 / アイドリッシュセブン | HEVC-10bit | 官方合集 </td><td class="embedded" style="text-align: right; "><a href="download.php?id=338389"><div class="icons download ml-4 mb-4" title="下载本种"></div></a><br><a id="bookmark0" href="javascript: bookmark(338389,0);"><div class="icons delbookmark ml-2" style="display: inline-block" title="收藏"></div></a></td>
</tr></tbody></table></td><td class="rowfollow"><span title="无新评论">0</span></td><td class="rowfollow nowrap">2023-10-18<br>19:13:30</td><td class="rowfollow">49.32<br>GiB</td><td class="rowfollow"><b><a href="details.php?id=338389&amp;hit=1&amp;dllist=1#seeders"><span style="color: #ff0000">1</span></a></b></td>
<td class="rowfollow"><b><a href="details.php?id=338389&amp;hit=1&amp;dllist=1#leechers">49</a></b></td>
<td class="rowfollow">0</td>
<td class="rowfollow"><span class="nowrap"><a class="Uploader_Name" href="/userdetails.php?id=366418"><span style="font-weight: bold">ruoqin</span></a></span><br><a href="badges.php?action=owners&amp;bid=2469" target="_target" title="μ’s徽章"><span class="boot-label-red" title="点击显示详情">μ’s</span></a></td></tr>
```

**Comment by FovenX3** [comment]
应该是这个站title="不计下载量"导致的
[parse.go](https://github.com/sagan/ptool/blob/32c0fd87959301ea5fa12ce05d64a83f26de7d2e/site/nexusphp/parse.go#L390)

**Comment by FovenX3** [comment]
应该是这个站title="不计下载量"导致的
[parse.go](https://github.com/sagan/ptool/blob/32c0fd87959301ea5fa12ce05d64a83f26de7d2e/site/nexusphp/parse.go#L390)

···

<img class="pro_free" src="/pic/trans.gif" title="不计下载量" alt="">
<img class="pro_free2up" src="/pic/trans.gif" title="不计下载量且计2倍上传量" alt="">

···
u2的other 上传比率2.33X 下载比率0.00X 好像也不能识别为免费种

"byr": {
			Type:              "nexusphp",
			Url:               "https://byr.pt/",
			Comment:           "北邮人",
		},
全站无hr

**Comment by sagan** [comment]
改了下，应该修复了。

现在 SelectorTorrentFree 只要存在dom元素就认为是免费种子。

**Comment by FovenX3** [comment]
谢谢
我在windows下编译时出现了这个错误
```
go build
# github.com/sagan/ptool/client/transmission
client\transmission\transmission.go:761:19: cannot use []any{…} (value of type []any) as []string value in struct literal
```
release能更新windows的amd64二进制文件吗

**Comment by sagan** [comment]
u2 我自己试是可以的。SelectorTorrentFree 用的是 `*[alt="下載比率"] + b:contains("0.00X")`

最新的 snapshot 构建现在可以从 AppVeyor 获取：

https://ci.appveyor.com/project/sagan/ptool/build/artifacts

**Comment by FovenX3** [comment]
谢谢，原来是我u2语言为简体中文造成的，切换到翻译中文一切正常
