### ISSUE TITLE
可否添加象站的支持？

### ISSUE THREAD

**Issue by dingchundong** [sagan/ptool#8]
死活拉不到DOM,似乎是和五秒盾过不去，然后vps下载了个firefox并且登录拉取cookie依然无法获取页面，希望您可以考虑怎么设置，谢谢！

**Comment by sagan** [comment]
首先确认用浏览器正常访问种子列表页面时是不是也频繁出现5秒盾。这种情况目前没有任何办法，未来我考虑是否给程序增加 [FlareSolverr](https://github.com/FlareSolverr/FlareSolverr) 支持。

如果浏览器正常（只有第一次访问有5秒盾，之后很长时间都没有），那么关键是要让ptool使用的 cookie、ip、ua 和浏览器环境完全一致，在 ptool.toml 的 [[site]] 站点配置里：

* userAgent = “” 指定为浏览器 UA
* proxy = "" 指定为浏览器使用的代理。例如 http://localhost:1080, socks5://localhost:7890
* 从对应的浏览器里提取 cookie。注意直接从 F12 的 Network tab 的request header 里复制。

**Comment by sagan** [comment]
我去求一个邀请进站看一下吧。
