### ISSUE TITLE
批量下载种子的无法指定从哪页开始

### ISSUE THREAD

**Issue by LevineWoo** [sagan/ptool#9]
win端，因为馒头的有页面刷新限制，想直接从电子书的第5页按小到大排序的开始，但我把url除域名部分的后面的粘贴进去。命令如下：
./ptool batchdl mteam --action add --add-client qbittorrent --max-torrents 10000 --base-url "torrents.php?inclbookmarked=0&incldead=1&spstate=0&cat=427&&sort=5&type=asc&page=6"

无法从第6页开始，仍然是从首页开始。

**Comment by sagan** [comment]
用 ```--start-page 6``` 参数指定起始页数。但注意：

batchdl 会设置 url 的 sort & type & page 字段，并且 type 排序字段是反转的，例如默认 --sort size --order asc 设置下，实际访问的 url 是 baseUrl +  "sort=5&type=desc&page=XX"，XX从结果的最后1页（或 --start-page 指定的初始页面）开始往前遍历。这样做目的是跳过置顶种子。

所以你的场景 --start-page 应该设为 42 (倒数第6页)。batchdl 命令结束时会显示本次遍历到的最后页的页数(LastPage)。
